language: php

php:
 - 5.4
 - 5.5
 - 5.6
 - 7.0
 - 7.1
 - hhvm
matrix:
    allow_failures:
     - php: 7.0
     - php: 7.1

addons:
    code_climate:
        repo_token:
            secure: "F0tPpoTZPMJkyQsElb2UKekfAcvE4P7/kAfW6/9sUF3jgNaRfob0kAyXAxf99n09+M5fI8VlFC0OEpmKGHUXez9EFMAqFeZ85eMePvXOX6EmloCPUY3LcX0tGefFQn402tSZCMdIzXwsjTYe5Ku4bGsH+etXRViX+teZmct7BBQ="

services:
 - memcached
 - redis-server

before_script:
 - pecl install memcache
 - pecl install memcached
 - pecl install redis
 - composer self-update || true
 - composer install
 - ./tests/travis/mysql-setup.sh

script: phpunit

after_script:
  - vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
  - vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
